name: yandex_mapkit_example
description: Demonstrates how to use the yandex_mapkit plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  yandex_mapkit:
    path: ../
  geolocator: ^10.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  assets:
    - lib/assets/bin_person.png
    - lib/assets/route_bin.png
    - lib/assets/full_bin.png
    - lib/assets/empty_bin.png
    - lib/assets/user.png
    - lib/assets/cluster.png
    - lib/assets/pngwing.png
    - lib/assets/avatar.png
    - lib/assets/place.png
    - lib/assets/arrow.png
    - lib/assets/route_start.png
    - lib/assets/route_stop_by.png
    - lib/assets/route_end.png
  uses-material-design: true
